#!/bin/bash
cd ../..
git clone git@github.com:dgreco/graphbase.git graphbase-pages
cd graphbase-pages
git symbolic-ref HEAD refs/heads/gh-pages
rm .git/index
git clean -fdx
mkdir repository

cat >> update-directory-index.sh <<EOF
#!/bin/bash
 
for DIR in $(find ./repository -type d); do
  (
    echo -e "<html>\n<body>\n<h1>Directory listing</h1>\n<hr/>\n<pre>"
    ls -1pa "\${DIR}" | grep -v "^\./$" | grep -v "^index\.html$" | awk '{ printf "<a href=\"%s\">%s</a>\n",\$1,\$1 }'
    echo -e "</pre>\n</body>\n</html>"
  ) > "\${DIR}/index.html"
done

git add -A
git commit -m "Updated Repository"
git push origin gh-pages

EOF

chmod +x update-directory-index.sh